accounts/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name="register"),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.create_poll, name='create_poll'),
    path('poll/<slug:slug>/', views.poll_detail, name='poll_detail'),
    path('poll/<slug:slug>/vote', views.poll_vote, name='poll_vote'),
    path('poll/<slug:slug>/results', views.poll_results, name='poll_results'),
    path('polls/dashboard', views.polls_dashboard, name='polls_dashboard'),
    path('poll/<slug:slug>/delete', views.delete_poll, name='delete_poll'),
]

polls_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('account/', include('accounts.urls'))
]

polls/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings


class Question(models.Model):
    text = models.TextField(max_length=200)
    slug = models.SlugField(unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE,
                             blank=True,
                             null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.text[0:10]) + "-" + str(self.id)
            self.save()

    def get_absolute_url(self):
        return reverse('polls:poll_detail',
                       args=[self.slug])

    def get_results_url(self):
        return reverse('polls:poll_results',
                       args=[self.slug])


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE,
                                 related_name='answers')
    answer_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords are different')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

polls/forms.py
from django import forms
from .models import Question, Answer
from django.forms import modelformset_factory


class QuestionModelForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']
        widgets = {'text': forms.Textarea(attrs={'class': 'form-control question-form',
                                                 'placeholder': "Enter question",
                                                 'label': 'Poll question'})}


class AnswerModelForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['answer_text']


AnswerFormset = modelformset_factory(Answer,
                                     fields=['answer_text'],
                                     extra=1,
                                     widgets={'answer_text': forms.TextInput(attrs={'class': 'form-control answer-form',
                                                                                    'placeholder': 'Enter answer',
                                                                                    'label': 'Poll answer'})})

accounts/views.py
from django.shortcuts import render
from .forms import UserRegistrationForm


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'accounts/user/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'accounts/user/register.html', {'user_form': user_form})

polls/views.py
from django.shortcuts import render, get_object_or_404
from .forms import QuestionModelForm, AnswerFormset
from .models import Question, Answer
from django.shortcuts import redirect, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def create_poll(request):
    if request.method == 'GET':
        question_form = QuestionModelForm(request.GET or None)
        answer_formset = AnswerFormset(queryset=Answer.objects.none())
    elif request.method == 'POST':
        question_form = QuestionModelForm(request.POST)
        answer_formset = AnswerFormset(request.POST)
        if question_form.is_valid() and answer_formset.is_valid():
            question = question_form.save(commit=False)
            if request.user.is_authenticated:
                question.user = request.user
            else:
                question.user = None
            question.save()
            for form in answer_formset:
                answer = form.save(commit=False)
                answer.question = question
                answer.save()
            return redirect(question.get_absolute_url())
    return render(request, 'polls/create_poll.html', {'question_form': question_form,
                                                      'answer_formset': answer_formset})


def poll_detail(request, slug):
    poll = get_object_or_404(Question, slug=slug)
    answers = poll.answers.all()

    return render(request, 'polls/poll_detail.html', {'poll': poll,
                                                      'answers': answers})


def poll_vote(request, slug):
    poll = get_object_or_404(Question, slug=slug)
    answers = poll.answers.all()

    if f'vote_cookie_{poll.id}' in request.COOKIES.keys():
        return render(request, 'polls/poll_detail.html', {'poll': poll,
                                                          'answers': answers,
                                                          'error_message': "You already voted!"})
    else:
        try:
            selected_answer = poll.answers.get(pk=request.POST['answer'])
        except(KeyError, Answer.DoesNotExist):
            return render(request, 'polls/poll_detail.html', {'poll': poll,
                                                              'answers': answers,
                                                              'error_message': "Error!"})
        else:
            selected_answer.votes += 1
            selected_answer.save()
            response = HttpResponseRedirect(reverse('polls:poll_results', args=[poll.slug]))
            response.set_cookie(f'vote_cookie_{poll.id}', str(poll.id))
            return response


def poll_results(request, slug):
    poll = get_object_or_404(Question, slug=slug)
    return render(request, 'polls/poll_results.html', {'poll': poll})


@login_required
def polls_dashboard(request):
    polls = Question.objects.filter(user=request.user)
    return render(request, 'polls/polls_dashboard.html', {'polls': polls})


@login_required
def delete_poll(request, slug):
    poll = get_object_or_404(Question, slug=slug)
    poll.delete()
    return redirect('polls:polls_dashboard')

accounts/templates/accounts/user/register.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css  %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <header>
        <div class="header-text">
            <h1>Register</h1>
            <p>If you already have an account, <a href="{% url 'login' %}">you can login here</a></p>
        </div>
    </header>

    <form action="." method="post">
        {% csrf_token %}
        <div class="form-container">
            <div class="form-div">
                {{ user_form.as_p }}
            </div>
            <p><input type="submit" value="Create an account" class="submit-button"></p>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/user/register_done.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css  %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block content %}
    <div class="form-container">
        <h1>Hello, {{ new_user.username }}</h1>
        <p>Your account is now active, you can <a href="{% url 'login' %}">log in here</a></p>
    </div>
{% endblock %}

polls/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Polls website{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script src="https://kit.fontawesome.com/49b5438e0f.js" crossorigin="anonymous"></script>
    {% block extra_css %}
    {% endblock %}
</head>
<body>

<div class="sidenav">
	<a href="{% url 'polls:create_poll' %}"><span>|</span> Create poll</a>
    {% if user.is_authenticated %}
        <a href="{% url 'polls:polls_dashboard' %}"><span>|</span> My polls</a>
        <a href="{% url 'logout' %}"><span>|</span> Log out</a>
    {% else %}
        <a href="{% url 'login' %}"><span>|</span> Log in</a>
    {% endif %}
</div>

{% block content %}

{% endblock %}
</body>

{% block extra_js %}

{% endblock %}
</html>

polls/templates/polls/create_poll.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            strona
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {% block extra_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/create_poll.css' %}">
        {% endblock %}
    </head>


<body>
{% block content %}

<header>
    <div class="header-text">
        {% if user.is_authenticated %}
        {% else %}
            <div class="info">
                <span><i class="fas fa-info-circle"></i>&nbsp;&nbsp;&nbsp; log in to assign polls to your account
                    and have them listed in your dashboard </span>
            </div>
        {% endif %}
        <h1>Create <span class="name-color">your</span> poll</h1>
    </div>
</header>

<section>
        <form method="POST" action="" class="create-poll-form">
            <div class="create-poll">
                {% csrf_token %}

                {{ question_form.text  }}

                {{ answer_formset.management_form }}
                {% for form in answer_formset %}
                <div class="form-row answer-form-div">
                    {{ form.as_p }}
                </div>
                {% endfor %}
                <div class="form-row answer-form-div" id="empty-row" style="display: none">
                    {{ answer_formset.empty_form.as_p }}
                </div>
                <div>
                    <input type="submit" value="Save poll" class="submit-button">
                    <a class="add-new-form" href="#"><button class="add-answer"><i class="fas fa-plus"></i></button> Add answer</a>
                </div>
            </div>
        </form>
</section>

{% endblock %}
</body>

{% block extra_js %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://code.jquery.com/color/jquery.color/jquery.color-2.1.2.min.js"></script>
<script type='text/javascript'>

    function updateEmptyFormIDs(element, totalForms){
        let thisInput = element
        let currentName = element.attr('name')
        let newName = currentName.replace(/__prefix__/g, totalForms)

        thisInput.attr('name', newName)
        thisInput.attr('id', "id_" + newName)

        let newFormRow = element.closest(".form-row");
        let newRowId = "row_id_" + newName
        newFormRow.attr("id", newRowId)

        newFormRow.addClass("new-parent-row")
        let parentDiv = element.parent();
        parentDiv.attr("id", "parent_id_" + newName)

        let inputLabel = parentDiv.find("label")
        inputLabel.attr("for", "id_" + newName)

        return newFormRow
    }

    $('.add-new-form').click(function(e) {
        e.preventDefault()
        let formId = "id_form-TOTAL_FORMS"
        let emptyRow = $("#empty-row").clone();
        emptyRow.attr("id", null)
        emptyRow.removeAttr("style")
        let totalForms = parseInt($('#' + formId).val());
        let newFormRow;
        emptyRow.find("input, select, textarea").each(function (){
            newFormRow = updateEmptyFormIDs($(this), totalForms)
        })

        $(".form-row:last").after(newFormRow)

        $('#' + formId).val(totalForms + 1);

        $('html, body').animate({
            scrollTop: newFormRow.offset().top - 100
        }, 500, function(){
            newFormRow.animate({
                backgroundColor: "#fff"
            }, 1500)
        });
    });

</script>

{% endblock %}

polls/templates/polls/poll_detail.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vote</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% block extra_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/poll_detail.css' %}">
    {% endblock %}
</head>
<body>
{% block content %}

<header>
    <div class="header-text">
        <h1>Voting screen</h1>
    </div>
</header>

<section>
    <div class="vote-form">
        <div class="poll-question">
            {{ poll.text }}
        </div>

        <div>
            <form action="{% url 'polls:poll_vote' poll.slug %}" method="POST">
                {% csrf_token %}
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <div class="poll-answers">
                    {% for answer in answers %}
                        <label>
                            <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}">
                            <span>{{ answer.answer_text }}</span>
                        </label>
                    {% endfor %}
                </div>
                <input type="submit" value="vote" class="submit-button">
            </form>
        </div>

        <div>
            <p>Share poll: {{ request.get_host }}{{ poll.get_absolute_url }}</p>
        </div>
    </div>
</section>

{% endblock %}
</body>
</html>

polls/templates/polls/poll_results.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block extra_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/poll_results.css' %}">
    {% endblock %}
</head>
<body>
{% block content %}

<header>
    <div class="header-text">
        <h1>Results</h1>
    </div>
</header>

<section>
    <div class="container">
        <div class="poll-question">
            {{ poll.text }}
        </div>
        <div class="poll-results">
            {% for answer in poll.answers.all %}
                <p>{{ answer.answer_text }} - <span class="number">{{ answer.votes }}</span></p>
            {% endfor %}
        </div>
        <div>
            <p>Share poll: {{ request.get_host }}{{ poll.get_absolute_url }}</p>
        </div>
    </div>

</section>


{% endblock %}
</body>
</html>

polls/templates/polls/polls_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load poll_extras %}
<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            strona
        </title>
        <meta name="description" content="" />
        {% block extra_css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/polls_dashboard.css' %}">
        {% endblock %}
    </head>

<body>
{% block content %}

<header>
    <div class="header-text">
        <h1>Your <span class="name-color">polls</span></h1>
    </div>
</header>

<section>
    <div class="table-div">
        <table class="rwd-table">
            <thead>
                <tr>
                    <th>Date created</th>
                    <th>Question</th>
                    <th>Top answer</th>
                    <th>Show answers</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for poll in polls %}
                <tr>
                    <td data-th="Date created">{{ poll.date_created |date:"D, j-n-Y" }}</td>
                    <td data-th="Question">{{ poll.text }}</td>
                    <td data-th="Top answer">{% get_top_answer poll %}</td>
                    <td data-th="Show answers"><a href="{{ poll.get_results_url }}">Show answers</a></td>
                    <td data-th="Delete">
                        <form method="POST" action="{% url 'polls:delete_poll' poll.slug %}">
                            {% csrf_token %}
                            <input type="submit" value="Delete">
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>


{% endblock %}
</body>